config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'


  resources :home do
    get 'index'
    get 'show'
  end

  get 'users/my_profile'  => 'users#my_profile'
  get 'admin' => 'admin/home#index'
  namespace :admin do
    resources :pages do
      member do
        get 'preview'
        get 'change_columns_layout'
        get 'change_module'
        get 'add_section'
      end
    end
    resources :users do
      member do
        post 'update_password'
        get 'update_locale'
        get 'my_password'
      end
    end
    resources :pictures
    resources :posts
    resources :categories
    resources :menus do
      member do
        post 'append_links'
        put 'toggle_suspend_menu'
      end
    end
  end
end

app/models/admin/picture.rb
class Admin::Picture < ApplicationRecord
  has_attached_file :file, styles: { small: "170x170>", thumb: "50x50>" }, default_url: "/assets/no-image.png"
  validates_attachment_content_type :file, content_type: /\Aimage\/.*\z/

  has_many :posts
end

app/controllers/admin/pictures_controller.rb
class Admin::PicturesController < AdminController
  before_action :set_admin_picture, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token, :only => [:create]

  def index
    @pictures = Admin::Picture.order('created_at')
  end

  def show
  end

  def new
  end

  def edit

  end

  def create
    @picture = Admin::Picture.new(picture_params)
    respond_to do |format|
      if @picture.save
        format.html { redirect_to admin_pictures_url, notice: t('.successfully_created') }
      else
        format.html { render :index }
      end
    end
  end

  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to admin_pictures_url, notice: t('.successfully_updated') }
      else
        format.html { render :index }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @picture.destroy
        format.html { redirect_to admin_pictures_url, notice: t('.successfully_destroyed') }
      end
    end
  end

  private
    def set_admin_picture
      @picture = Admin::Picture.find(params[:id])
    end

    def picture_params
      params.require(:admin_picture).permit(
          :file,
          :title,
          :alt
      )
    end
end

app/views/admin/pictures/_edit_picture_modal.html.erb
<div id="edit-picture-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">
          <%= t '.modal_title_edit_picture' %>
        </h4>
      </div>
      <div class="modal-body">
      </div>
    </div>
  </div>
</div>

app/views/admin/pictures/_form.html.erb
<%= form_for(@picture, html: { class: "main-form clearfix", id: "picture-form" }) do |f| %>
  <div class="pull-left center-630" style="width:17rem">
    <div class="content-flex">
      <%= image_tag @picture.file(:small), onerror:"this.onerror=null;this.src='#{image_url('no-image.png')}';" %>
    </div>
  </div>
  <div class="pull-left form-content-next-thumbnail">
    <div class="row">
      <div class="col-md-12">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <%= f.label :alt %>
        <%= f.text_field :alt %>
      </div>
    </div>
    <div class="pull-right">
      <%= f.submit nil, class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/admin/pictures/_gallery.html.erb
<div class="row gallery">
  <% @pictures.each do |picture| %>
    <div class="col-lg-2 col-sm-3 col-xs-6">
      <div class="box-gallery">
        <div class="content-flex">
          <%= image_tag picture.file(:small), onerror:"this.onerror=null;this.src='#{image_url('no-image.png')}';", data: {id: picture.id} %>
        </div>
        <% if controller_name == 'pictures' %>
          <nav>
            <ul>
              <li>
                <%= link_to edit_admin_picture_path(picture), :class => 'btn edit-picture' do %>
                    <%= material_icon.mode_edit %>
                <% end %>
              </li>
              <li>
                <%= link_to admin_picture_path(picture), method: :delete, data: { confirm: t('confirm_delete') }, :class => 'btn' do %>
                    <%= material_icon.delete %>
                <% end %>
              </li>
            </ul>
          </nav>
        <% end %>
      </div>
    </div>
  <% end %>
  <%= form_for Admin::Picture.new, remote: true do |f| %>
      <div class="col-lg-2 col-sm-3 col-xs-6">
        <div class="box-gallery">
          <%= f.label :file, class: "drop-target" do %>
              <%= material_icon.cloud_upload %>
          <% end %>
          <%= f.file_field :file, class: "hidden drop-input" %>
        </div>
      </div>
  <% end %>
</div>

<%= render 'admin/pictures/edit_picture_modal' %>

app/views/admin/pictures/edit.js.erb
$("#edit-picture-modal").modal("show");
$("#edit-picture-modal .modal-body").html("<%= j render 'admin/pictures/form' %>");

app/views/admin/pictures/index.html.erb
<header id="page-header">
  <div class="container">
    <h1><%= t '.page_title' %></h1>
    <p class="subtitle">
      <%= t '.page_description' %>
    </p>
  </div>
</header>

<% if flash[:alert] %>
    <div class="container">
      <p class="alert alert-danger">
        <%= flash[:alert] %>
      </p>
    </div>
<% end %>
<% if flash[:notice] %>
    <div class="container">
      <p class="alert alert-success">
        <%= flash[:notice] %>
      </p>
    </div>
<% end %>

<section class="clearfix">
  <div class="container">
    <div class="white-content clearfix">
      <h2>
        <%= t '.gallery_explication' %>
      </h2>
      <%= render 'gallery' %>
    </div>
  </div>
</section>