config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'


  resources :home do
    get 'index'
    get 'show'
  end

  get 'users/my_profile'  => 'users#my_profile'
  get 'admin' => 'admin/home#index'
  namespace :admin do
    resources :pages do
      member do
        get 'preview'
        get 'change_columns_layout'
        get 'change_module'
        get 'add_section'
      end
    end
    resources :users do
      member do
        post 'update_password'
        get 'update_locale'
        get 'my_password'
      end
    end
    resources :pictures
    resources :posts
    resources :categories
    resources :menus do
      member do
        post 'append_links'
        put 'toggle_suspend_menu'
      end
    end
  end
end

app/models/admin/category.rb
class Admin::Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  belongs_to :category, foreign_key: :parent_id
  has_many :posts , :through => :categorizations
  has_many :categorizations
  has_many :menus , :through => :items_relationships
  has_many :items_relationships

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  before_action :set_admin_category, only: [:show, :edit, :update, :destroy]
  after_action :nil_post_category, only: [:destroy]

  def index
    @categories = Admin::Category.all
  end

  def show
  end

  def new
    @category = Admin::Category.new
  end

  def edit
  end

  def create
    @category = Admin::Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_categories_url, notice: t('.successfully_created') }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_categories_url, notice: t('.successfully_updated') }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @category.destroy
        format.html { redirect_to admin_categories_url, notice: t('.successfully_destroyed') }
      else
        format.html { redirect_to admin_categories_url, notice: t('.error_occured') }
      end
    end
  end

  private
    def set_admin_category
      @category = Admin::Category.find(params[:id])
    end

    def category_params
      params.require(:admin_category).permit(
          :name,
          :description,
          :parent_id
      )
    end

    def nil_post_category
      # @posts = Admin::Post.where(category_ids: nil)
      # @posts.each do |post|
      #   post.update(params[:category_ids] => 1)
      # end
    end
end

app/views/admin/categories/_form.html.erb
<section class="clearfix margin-bot-20">
  <div class="container">
    <div class="white-content">
      <%= form_for(@category, html: { class: "main-form clearfix", id: "category-form" }) do |f| %>
          <h2><%= t '.form_description' %></h2>
          <%= render 'admin/shared/error_messages', target: @category %>
          <div class="row">
            <div class="col-md-6">
              <%= f.label :name, class:"required" %>
              <%= f.text_field :name, required: true %>
            </div>
            <div class="col-md-6">
              <%= f.label :parent_id %>
              <%= f.select :parent_id, Admin::Category.all.map { |x| [x.name, x.id]},{prompt: true},class: "select2" %>
              <%# f.text_field :parent_id %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <%= f.label :description %>
              <%= f.text_area :description, rows: 5 %>
            </div>
          </div>
          <div class="pull-right">
            <%= f.submit nil, class: "btn btn-primary" %>
          </div>
      <% end %>
    </div>
  </div>
</section>

app/views/admin/categories/edit.html.erb
<header id="page-header">
  <div class="container">
    <h1>
      <%= @category.name %>
    </h1>
    <p class="subtitle">
      <%= t '.page_description' %>
    </p>
  </div>
</header>

<%= render 'form' %>

app/views/admin/categories/index.html.erb
<header id="page-header">
  <div class="container">
    <div class="pull-left">
      <h1><%= t '.page_title' %></h1>
      <p class="subtitle">
        <%= t '.page_description' %>
      </p>
    </div>
    <%= link_to t('.create_category'), new_admin_category_url , class: "pull-right btn btn-primary" %>
  </div>
</header>

<% if flash[:alert] %>
    <div class="container">
      <p class="alert alert-danger">
        <%= flash[:alert] %>
      </p>
    </div>
<% end %>
<% if flash[:notice] %>
    <div class="container">
      <p class="alert alert-success">
        <%= flash[:notice] %>
      </p>
    </div>
<% end %>

<section class="clearfix margin-bot-20">
  <div class="container">
    <div class="white-content">
      <div class="table-responsive">
        <table class="main-table datatable">
          <thead>
          <th width="30%"><%= t '.name' %></th>
          <th width="35%"><%= t '.description' %></th>
          <th width="25%"><%= t '.parent' %></th>
          <th width="10%"><%= t '.used_count' %></th>
          <th class="no-sorting" width="60"><%= t '.actions' %></th>
          </thead>
          <tbody>
          <% @categories.each do |category| %>
            <tr>
              <td>
                <%= category.name %>
              </td>
              <td>
                <%= category.description %>
              </td>
              <td>
                <% if category.category %>
                  <%= category.category.name %>
                <% end %>
              </td>
              <td>
                <%= category.post_ids.count %>
              </td>
              <td>
                <div style="width:72px!important">
                  <!-- EDIT -->
                  <%= link_to edit_admin_category_url(category), :class => 'btn btn-primary' do %>
                      <%= material_icon.mode_edit %>
                  <% end %>
                  <!-- DELETE -->
                  <%= link_to admin_category_url(category), method: :delete, data: { confirm: t('confirm_delete') }, :class => 'btn btn-danger' do %>
                      <%= material_icon.delete %>
                  <% end if category.id != 1 %>
                </div>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>