config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'


  resources :home do
    get 'index'
    get 'show'
  end

  get 'users/my_profile'  => 'users#my_profile'
  get 'admin' => 'admin/home#index'
  namespace :admin do
    resources :pages do
      member do
        get 'preview'
        get 'change_columns_layout'
        get 'change_module'
        get 'add_section'
      end
    end
    resources :users do
      member do
        post 'update_password'
        get 'update_locale'
        get 'my_password'
      end
    end
    resources :pictures
    resources :posts
    resources :categories
    resources :menus do
      member do
        post 'append_links'
        put 'toggle_suspend_menu'
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/categorization.rb
class Admin::Categorization < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/admin/category.rb
class Admin::Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  belongs_to :category, foreign_key: :parent_id
  has_many :posts , :through => :categorizations
  has_many :categorizations
  has_many :menus , :through => :items_relationships
  has_many :items_relationships

end

app/models/admin/items_relationship.rb
class Admin::ItemsRelationship < ApplicationRecord
  belongs_to :post
  belongs_to :category
  belongs_to :page
  belongs_to :menu
end

app/models/admin/menu.rb
class Admin::Menu < ApplicationRecord
  has_many :posts , :through => :items_relationships
  has_many :categories , :through => :items_relationships
  has_many :pages , :through => :items_relationships
  has_many :items_relationships
end

app/models/admin/page.rb
class Admin::Page < ApplicationRecord

  after_initialize :set_default_source

  validates :name, presence: true, uniqueness: true
  validates :meta_description, presence: true
  validates :page_title, presence: true

  has_many :menus , :through => :items_relationships
  has_many :items_relationships

  def set_default_source
    if source.blank?
      default_source = AdminController.new.render_to_string(partial: 'admin/pages/editor/default_source')
      self.source = default_source
    end
  end

end

app/models/admin/picture.rb
class Admin::Picture < ApplicationRecord
  has_attached_file :file, styles: { small: "170x170>", thumb: "50x50>" }, default_url: "/assets/no-image.png"
  validates_attachment_content_type :file, content_type: /\Aimage\/.*\z/

  has_many :posts
end

app/models/admin/post.rb
class Admin::Post < ApplicationRecord
  before_save :default_values

  validates :title, presence: true, uniqueness: true

  STATUS_TYPES = [
      'draft',
      'published'
  ]
  def default_values
    self.author ||= User.current_user.first_name+" "+User.current_user.last_name
  end

  has_many :categories , :through => :categorizations
  has_many :categorizations
  belongs_to :picture
  has_many :menus , :through => :items_relationships
  has_many :items_relationships

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify

  def translated_name
    I18n.t(name, scope: 'role')
  end
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { small: "170x170>", thumb: "50x50>" }, default_url: "/assets/no-image.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def self.current_user
    Thread.current[:user]
  end

  def self.current_user=(user)
    Thread.current[:user] = user
  end

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < AdminController

end

app/controllers/admin/menus_controller.rb
class Admin::MenusController < AdminController
  before_action :set_admin_menu, only: [:show, :edit, :update, :destroy]
  before_action :set_admin_menu_elements, only: [:new, :edit]

  def index
    @menus = Admin::Menu.all
  end

  def show
  end

  def new
    @menu = Admin::Menu.new
  end

  def edit
  end

  def create
    @menu = Admin::Menu.new(menu_params)
    respond_to do |format|
      if @menu.save
        format.html { redirect_to admin_menus_url, notice: t('.successfully_created') }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to admin_menus_url, notice: t('.successfully_updated') }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @menu.destroy
        format.html { redirect_to admin_menus_url, notice: t('.successfully_destroyed') }
      else
        format.html { redirect_to admin_menus_url, notice: t('.error_occured') }
      end
    end
  end

  def toggle_suspend_menu

  end

  def append_links
    binding.pry
    @item_array = JSON.parse(params[:item_array])
  end

  private
    def set_admin_menu
      @menu = Admin::Menu.find(params[:id])
    end

    def set_admin_menu_elements
      @pages = Admin::Page.all
      @posts = Admin::Post.all
      @categories = Admin::Category.all
    end

    def menu_params
      params.require(:admin_menu).permit(
          :name,
          :active
      )
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :authorized?, if: :current_user
  layout 'admin_panel'

  private
    def authorized?
      if !current_user.has_role? :admin
        redirect_to(root_url)
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  protect_from_forgery with: :exception
  before_action :set_locale
  before_filter :set_current_user, if: :current_user

  def after_sign_in_path_for(resource)
    if current_user.has_role? :admin
      admin_url
    else
      root_path
    end
  end

  def set_current_user
    User.current_user = current_user
  end

  def set_locale
    if current_user.present? && current_user.locale?
      I18n.locale = current_user.locale
    else
      I18n.locale = extract_locale_from_accept_language_header || I18n.default_locale
    end
  end

  private
    def layout_by_resource
      if devise_controller?
        'devise'
      else
        'application'
      end
    end

    def extract_locale_from_accept_language_header
      request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_page, only: [:show]

  def index
    @menu = Admin::Menu.where(active: true).first
    # @pages = Admin::Page.all
    # @page = @pages.where(is_index: true).first
  end

  def show

  end

  private
  def set_page
    # @page = Admin::Page.find(params[:id])
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/layouts/_main_header.html.erb
<header id="main-header">
  <div id="company-data" class="clearfix">
    <div class="pull-left">
      a
    </div>
    <i class="material-icons pull-right" id="min-nav-btn">
      format_indent_decrease
    </i>
    <i class="material-icons" id="burger-menu-close">
      close
    </i>
  </div>
  <nav id="main-nav">
    <ul>
      <div>
        <li>
          <h2><%= t '.overview' %></h2>
        </li>
        <li>
          <%= link_to admin_url do %>
            <%= material_icon.home %>
            <p><%= t '.home' %></p>
          <% end %>
        </li>
      </div>
      <div>
        <li>
          <h2><%= t '.users' %></h2>
        </li>
        <li>
          <%= link_to admin_users_url do %>
              <%= material_icon.people %>
              <p><%= t '.users' %></p>
          <% end %>
        </li>
        <li>
          <%= link_to edit_admin_user_url(current_user) do %>
              <%= material_icon.face %>
              <p><%= t '.my_profile' %></p>
          <% end %>
        </li>
      </div>
      <div>
        <li>
          <h2><%= t '.content' %></h2>
        </li>
        <li>
          <%= link_to admin_pictures_url do %>
              <%= material_icon.camera_alt %>
              <p><%= t '.media' %></p>
          <% end %>
        </li>
        <li>
          <%= link_to admin_pages_url do %>
              <%= material_icon.description %>
              <p><%= t '.pages' %></p>
          <% end %>
        </li>
        <li>
          <%= link_to admin_posts_url do %>
              <%= material_icon.recent_actors %>
              <p><%= t '.posts' %></p>
          <% end %>
        </li>
        <li>
          <%= link_to admin_categories_url do %>
              <%= material_icon.flag %>
              <p><%= t '.categories' %></p>
          <% end %>
        </li>
        <li>
          <%= link_to admin_menus_url do %>
              <%= material_icon.flag %>
              <p><%= t '.menus' %></p>
          <% end %>
        </li>
      </div>
    </ul>
  </nav>
</header>

app/views/admin/layouts/_page_loader.html.erb
<div class="page-loader">
  <div class="line one"></div>
  <div class="line two"></div>
  <div class="line three"></div>
  <div class="line four"></div>
  <div class="line five"></div>
</div>

app/views/admin/layouts/_second_header.html.erb
<header id="second-header">
  <div class="page">
      <div class="container">
        <ul id="header-user-shortcuts">
          <li>
            <i class="material-icons" id="burger-menu-open">menu</i>
          </li>
          <li id="locale">
            <% if current_user.locale == "en" %>
              <%= link_to "", "#!", class: "flag-icon flag-icon-gb" %>
            <% else %>
              <%= link_to "", "#!", class: "flag-icon flag-icon-#{current_user.locale}" %>
            <% end %>
            <ul>
              <h4>
                <%= t '.langue' %>
              </h4>
              <div class="content">
                <% @locales = ["fr","en"] %>
                <% @locales.each do |locale| %>
                    <li>
                      <%= link_to controller: 'users', action: 'update_locale', id: locale do %>
                          <% if locale == "en" %>
                            <i class="flag-icon flag-icon-gb"></i>
                          <% else %>
                              <i class="flag-icon flag-icon-<%= locale %>"></i>
                          <% end %>
                          <%= t(locale) %>
                      <% end %>
                    </li>
                <% end %>
              </div>
            </ul>
          </li>
        </ul>
        <ul id="user-data">
          <li>
            <a href="#!">
              <div class="content-flex avatar-thumbnail pull-left">
                <%= image_tag current_user.avatar(:thumb), onerror:"this.onerror=null;this.src='#{image_url('no-image.png')}';" %>
              </div>
              <p class="pull-left">
                <span class="hide-630"><%= current_user.first_name %> <%= current_user.last_name %></span>
                <%= material_icon.keyboard_arrow_down %>
              </p>
            </a>
            <ul>
              <li class="user-profile">
                <div class="content-flex pull-left">
                  <%= image_tag current_user.avatar(:small), onerror:"this.onerror=null;this.src='#{image_url('no-image.png')}';" %>
                </div>
                <div class="pull-left">
                  <p>
                    <%= current_user.first_name %> <%= current_user.last_name %>
                    <span><%= current_user.email%></span>
                  </p>
                  <%= link_to t('.edit_my_profile'), edit_admin_user_url(current_user) %>
                </div>
              </li>
              <li class="user-shortcut">
                <ul>
                  <li>
                    <%= link_to t('.change_my_password'), my_password_admin_user_url(current_user) %>
                  </li>
                </ul>
              </li>
              <li class="user-logout">
                <%= link_to( t('.logout'), destroy_user_session_path, :method => :delete, class: "btn btn-primary") %>
              </li>
            </ul>
          </li>
        </ul>
      </div>
  </div>
</header>

app/views/admin/pages/_form.html.erb
<div class="white-content">
  <%= form_for @page, html: { class: "clearfix main-form" }  do |f| %>
      <h2><%= t '.form_description' %></h2>
      <!-- ERRORS -->
      <% if @page.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@page.errors.count, t('generic.error_while_saving.one'), t('generic.error_while_saving.other') ) %>
            </h2>
            <ul>
              <% @page.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div class="row">
        <div class="col-md-8">
          <div class="row">
            <div class="col-md-12">
              <%= f.label :name, class:"required" %>
              <%= f.text_field :name %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <%= f.label :page_title, class:"required" %> <span class="chars-count">(<span>70</span>)</span>
              <%= f.text_field :page_title %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <%= f.label :meta_description, class:"required" %> <span class="chars-count">(<span>156</span>)</span>
              <%= f.text_area :meta_description %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <%= f.check_box :is_index %>
              <%= f.label :is_index %></span>
            </div>
          </div>
          <div class="pull-right">
            <%= f.submit nil, :class => 'btn btn-primary' %>
          </div>
        </div>
        <aside class="col-md-4" id="browser-preview">
          <p class="page-title"><%= t '.page_title' %></p>
          <p class="page-url">
            <span>https://</span>
            <span class="domain-name"></span>
            <span class="page-name-slug"></span>
          </p>
          <p class="page-description"><%= t '.meta_description'%></p>
        </aside>
      </div>
  <% end %>
</div>

app/views/admin/pages/add_section.js.erb
var $current_container = $iframe.find(".current-container");
$current_container.after("<%= j render 'admin/pages/editor/main_container' %>");
$current_container.nextAll().animate({ top: "5.8rem"});

app/views/admin/pages/change_columns_layout.js.erb
$("#columns-modal").modal("hide");

var $columns_parent = $iframe.find(".current-container .module-container .row");

$columns_parent.empty();

<% eval(@layout).each do |layout| %>
  $columns_parent.append("<%= j render 'admin/pages/editor/module_container', {column_width: layout } %>");
<% end %>

app/views/admin/pages/change_module.js.erb
$("#modules-modal").modal("hide");
$("body").append("<%= j render 'admin/pages/editor/modules/module_choosen_modal', { module_choosen: @module } %>");
$iframe.find(".current-container").addClass("<%= @module %>-module");
$("#module-choosen").modal("show");

app/views/admin/pages/edit.html.erb
<%= render 'admin/pages/editor/columns_modal' %>
<%= render 'admin/pages/editor/modules_modal' %>
<%= render 'admin/pages/editor/form_container_settings_modal' %>
<section class="clearfix" id="page-builder">
  <article>
    <%= render 'admin/pages/editor/forms' %>
  </article>
  <article>
    <%= render 'admin/pages/editor/page_source' %>
  </article>
</section>

<script type="text/javascript" charset="utf-8">
    function show_settings_block(element) {
        element.prepend("<%= j render partial: 'admin/pages/editor/settings_blocks', locals: {page: @page} %>");
        element.nextAll().stop().animate({ top: "5.8rem"});
    }
    function hide_settings_block() {
        $iframe.find("#settings-blocks").remove();
        $iframe.find(".main-container").stop().animate({ top: 0});
    }

    $(document).ready(function () {
        $("iframe#preview-page-builder").on('load', function () {
            $iframe = $(this).contents();
            $iframe.on({
                mouseenter: function() {
                    show_settings_block($(this));
                },
                mouseleave: function() {
                    hide_settings_block();
                }
            }, ".main-container");

        })
    })
</script>

app/views/admin/pages/editor/modules/_module_blog.html.erb
gvbbj

app/views/admin/pages/editor/modules/_module_choosen_modal.html.erb
<div id="module-choosen" class="modal fade" data-module="<%= @module %>">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">
          <%= t ".modal_title_#{module_choosen}" %>
        </h4>
      </div>
      <div class="modal-body">
        <%= render "admin/pages/editor/modules/module_#{module_choosen}" %>
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal">
          <%= t '.finished' %>
        </button>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript" charset="utf-8">
    froala_params();
</script>

app/views/admin/pages/editor/modules/_module_form.html.erb
vhjvh

app/views/admin/pages/editor/modules/_module_image.html.erb
<%= render 'admin/pictures/gallery' %>

app/views/admin/pages/editor/modules/_module_slideshow.html.erb
vkbj

app/views/admin/pages/editor/modules/_module_text.html.erb
<nav>
  <ul class="nav nav-tabs">
    <li>
      <%= link_to t('.text'), '#code', data: {toggle: 'tab'} %>
    </li>
    <li class="active">
      <%= link_to t('.view'),'#view', data: {toggle: 'tab'} %>
    </li>
  </ul>
</nav>
<div class="tab-content main-form" id="page-settings-tabs">
  <div class="tab-pane active" id="view">
    <%= text_area_tag 'text_view',"",class: 'froala' %>
  </div>
  <div class="tab-pane" id="code">
    <div class="fake-header"></div>
    <%= text_area_tag 'text_code'%>
  </div>
</div>

app/views/admin/pages/editor/modules/_module_video.html.erb
bn

app/views/admin/pages/index.html.erb
<header id="page-header">
  <div class="container">
    <div class="pull-left">
      <h1><%= t '.page_title' %></h1>
      <p class="subtitle">
        <%= t '.page_description' %>
      </p>
    </div>
    <%= link_to "create new page", new_admin_page_url , class: "pull-right btn btn-primary" %>
  </div>
</header>

<% if flash[:alert] %>
    <div class="container">
      <p class="alert alert-error">
        <%= flash[:alert] %>
      </p>
    </div>
<% end %>
<% if flash[:notice] %>
    <div class="container">
      <p class="alert alert-success">
        <%= flash[:notice] %>
      </p>
    </div>
<% end %>

<section class="clearfix margin-bot-20">
  <div class="container">
    <div class="white-content">
      <table class="main-table datatable">
        <thead>
          <th><%= t '.page' %></th>
          <th><%= t '.page_url' %></th>
          <th class="no-sorting"><%= t '.actions' %></th>
        </thead>
        <tbody>
          <% @pages.each do |page| %>
            <tr>
              <td>
                image
                <%= page.name %>
                <% if page.is_index %>
                  <span>(Index)</span>
                <% end %>
              </td>
              <td>page.url</td>
              <td>
                <!-- EDIT -->
                <%= link_to edit_admin_page_path(page), :class => 'btn btn-primary' do %>
                    <%= material_icon.mode_edit %>
                <% end %>
                <!-- DELETE -->
                <%= link_to admin_page_path(page), method: :delete, data: { confirm: t('are_you_sure') }, :class => 'btn btn-danger' do %>
                    <%= material_icon.delete %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/admin/pages/preview.html.erb
<%= raw @page.source %>

app/views/admin/shared/_error_messages.html.erb
<% if target.errors.any? %>
  <div id="error-explanation">
    <h3>
      <%= pluralize(target.errors.count, t('error')) %>
      <%= t 'prohibited_record'%>:
    </h3>
    <ul>
      <% target.errors.messages.values.each do |message| %>
          <% message.each do  |msg| %>
              <li><%= msg %></li>
          <%end %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_js_locales_info.html.erb
<%= javascript_include_tag "i18n" %>
<%= javascript_include_tag "translations" %>
<%= javascript_tag do %>
    I18n.defaultLocale = "<%= I18n.default_locale %>";
    I18n.locale = "<%= I18n.locale %>";
    I18n.fallbacks = true;
<% end %>

app/views/layouts/admin_panel.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= controller.controller_name.humanize.capitalize %> | Admin </title>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
  <%= stylesheet_link_tag 'admin_panel', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'admin_panel', 'data-turbolinks-track': 'reload' %>
</head>

<body class="active-loader <%= controller.controller_name %> <%= controller.action_name %>">
  <%= render 'admin/layouts/main_header' %>
  <%= render 'admin/layouts/second_header' %>
  <%= render 'admin/layouts/page_loader' %>
  <div class="page">
    <%= yield %>
  </div>
  <%= render 'layouts/js_locales_info' %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%# @page.page_title.to_s %>s</title>
    <meta type="description" content="<%# @page.meta_description.to_s%>">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body id="front-content">
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Watermelon</title>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body id="admin-devise">
  <section class="clearfix">
    <div class="container">
      <%= yield %>
    </div>
  </section>
</body>
</html>