config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'


  resources :home do
    get 'index'
    get 'show'
  end

  get 'users/my_profile'  => 'users#my_profile'
  get 'admin' => 'admin/home#index'
  namespace :admin do
    resources :pages do
      member do
        get 'preview'
        get 'change_columns_layout'
        get 'change_module'
        get 'add_section'
      end
    end
    resources :users do
      member do
        post 'update_password'
        get 'update_locale'
        get 'my_password'
      end
    end
    resources :pictures
    resources :posts
    resources :categories
    resources :menus do
      member do
        post 'append_links'
        put 'toggle_suspend_menu'
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { small: "170x170>", thumb: "50x50>" }, default_url: "/assets/no-image.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def self.current_user
    Thread.current[:user]
  end

  def self.current_user=(user)
    Thread.current[:user] = user
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_admin_user, only: [:show, :edit, :update, :update_password, :my_password, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      generated_password = Devise.friendly_token.first(8)
      @user.password = generated_password
      @user.add_role params[:user][:roles]
      if @user.save
        UserMailer.welcome(@user, generated_password).deliver
        format.html { redirect_to admin_users_url, notice: t('.successfully_created') }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      @user.roles = []
      @user.add_role params[:user][:roles]
      if @user.update(user_params)
        format.html { redirect_to admin_users_url, notice: t('.successfully_updated') }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @user.destroy
        format.html { redirect_to admin_users_url, notice: t('.successfully_destroyed') }
      end
    end
  end

  def my_password

  end

  def update_password
    if @user.update_with_password(user_params_password)
      sign_in @user, :bypass => true
      format.html { redirect_to admin_url, notice: t('.successfully_updated') }
    else
      redirect_to my_password_admin_user_url
      flash[:alert] = t('.fail_change_password')
    end
  end

  def update_locale
    locale = params[:id]
    current_user.locale = locale
    current_user.save!
    redirect_to :back
  end

  private
    def set_admin_user
      @user = User.find(params[:id])
    end

    def user_params_password
      params.require(:user).permit(:current_password, :password, :password_confirmation, :locale)
    end

    def user_params
      params.require(:user).permit(
          :email,
          :first_name,
          :last_name,
          :avatar,
          :phone,
          :address,
          :city,
          :zip_code,
          #roles: []
      )
    end
end

app/views/admin/users/_form.html.erb
<% if flash[:alert] %>
    <div class="container">
      <p class="alert alert-danger">
        <%= flash[:alert] %>
      </p>
    </div>
<% end %>
<% if flash[:notice] %>
    <div class="container">
      <p class="alert alert-success">
        <%= flash[:notice] %>
      </p>
    </div>
<% end %>
<section class="clearfix margin-bot-20">
  <div class="container">
    <div class="white-content">
      <%= form_for(@user, url: {action: @user.new_record? ? "create" : "update"}, html: { class: "main-form clearfix", id: "user-form" }) do |f| %>
          <h2><%= t '.form_description' %></h2>
          <%= render 'admin/shared/error_messages', target: @user %>
          <div class="pull-left center-630" style="width:17rem">
            <div class="content-flex relative form-file">
              <%= image_tag @user.avatar(:small), onerror:"this.onerror=null;this.src='#{image_url('no-image.png')}';" %>
              <%= f.label :avatar do %>
                  <%= material_icon.cloud_upload %>
              <% end %>
              <%= f.file_field :avatar, class: "hidden" %>
            </div>
          </div>
          <div class="pull-left form-content-next-thumbnail" id="user-form">
            <div class="row">
              <div class="col-md-6">
                <%= f.label :first_name, class:"required" %>
                <%= f.text_field :first_name, required: true %>
              </div>
              <div class="col-md-6">
                <%= f.label :last_name, class:"required" %>
                <%= f.text_field :last_name, required: true %>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <%= f.label :role %>
                <%= f.select :roles, options_from_collection_for_select(Role.all, :name, :translated_name), {}, class: "select2" %>
              </div>
              <div class="col-md-6">
                <%= f.label :email, class:"required" %>
                <%= f.text_field :email, required: true %>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <%= f.label :phone %>
                <%= f.text_field :phone, class: "no-spaces" %>
              </div>
              <div class="col-md-6">
                <%= f.label :address %>
                <%= f.text_field :address %>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <%= f.label :city %>
                <%= f.text_field :city %>
              </div>
              <div class="col-md-6">
                <%= f.label :zip_code %>
                <%= f.text_field :zip_code, class: "no-spaces" %>
              </div>
            </div>
            <div class="pull-right">
              <%= f.submit class: "btn btn-primary" %>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</section>

app/views/admin/users/index.html.erb
<header id="page-header">
  <div class="container">
    <div class="pull-left">
      <h1><%= t '.page_title' %></h1>
      <p class="subtitle">
        <%= t '.page_description' %>
      </p>
    </div>
    <%= link_to t('.create_user'), new_admin_user_url , class: "pull-right btn btn-primary" %>
  </div>
</header>

<% if flash[:alert] %>
    <div class="container">
      <p class="alert alert-danger">
        <%= flash[:alert] %>
      </p>
    </div>
<% end %>
<% if flash[:notice] %>
    <div class="container">
      <p class="alert alert-success">
        <%= flash[:notice] %>
      </p>
    </div>
<% end %>

<section class="clearfix margin-bot-20">
  <div class="container">
    <div class="white-content">
      <div class="table-responsive">
        <table class="main-table datatable">
          <thead>
            <th class="no-sorting no-padding-right no-border-right" width="8%"><%= t '.user' %></th>
            <th class="no-padding-left no-border-left">&nbsp</th>
            <th><%= t '.contact' %></th>
            <th><%= t '.address' %></th>
            <th width="70"><%= t '.admin' %></th>
            <th class="no-sorting" width="60"><%= t '.actions' %></th>
          </thead>
          <tbody>
          <% @users.each do |user| %>
              <tr>
                <td class="no-padding-right no-border-right">
                  <div class="content-flex avatar">
                    <%= image_tag user.avatar(:thumb), onerror:"this.onerror=null;this.src='#{image_url('no-image.png')}';" %>
                  </div>
                </td>
                <td class="no-padding-left no-border-left capitalize-text">
                  <%= user.first_name %>
                  <%= user.last_name %>
                </td>
                <td>
                  <a href="mailto:<%= user.email %>" class="mailto">
                    <%= user.email %>
                  </a>
                </td>
                <td>
                  <%= user.address %><br>
                  <%= user.city %>,
                  <%= user.zip_code %>
                </td>
                <td class="center-text ">
                  <i class="material-icons chip <%= user.has_role? :admin %>">
                    fiber_manual_record
                  </i>
                  <p class="hidden"><%= user.roles %></p>
                </td>
                <td>
                  <div style="width:72px!important">
                    <!-- EDIT -->
                    <%= link_to edit_admin_user_path(user), :class => 'btn btn-primary' do %>
                        <%= material_icon.mode_edit %>
                    <% end %>
                    <!-- DELETE -->
                    <%= link_to admin_user_path(user), method: :delete, data: { confirm: t('confirm_delete') }, :class => 'btn btn-danger' do %>
                        <%= material_icon.delete %>
                    <% end if current_user != user %>
                  </div>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>

app/views/admin/users/my_password.html.erb
<header id="page-header">
  <div class="container">
    <h1>
      <%= @user.first_name %>
      <%= @user.last_name %>
    </h1>
    <p class="subtitle">
      <%= t '.page_description' %>
    </p>
  </div>
</header>

<% if flash[:alert] %>
    <div class="container">
      <p class="alert alert-danger">
        <%= flash[:alert] %>
      </p>
    </div>
<% end %>
<% if flash[:notice] %>
    <div class="container">
      <p class="alert alert-success">
        <%= flash[:notice] %>
      </p>
    </div>
<% end %>

<section class="clearfix">
  <div class="container">
    <div class="white-content">
      <%= form_for(@user, url: "update_password", html: { class: "main-form clearfix", id: "update-password-form" }, :method => :POST) do |f| %>
          <h2><%= t '.form_description' %></h2>
          <%= render 'admin/shared/error_messages', target: @user %>
          <div class="row">
            <div class="col-md-4">
              <%= f.label :current_password, class: "required" %>
              <%= f.password_field :current_password, autocomplete: "off", required: true %>
            </div>
            <div class="col-md-4">
              <%= f.label :password, class: "required" %>
              <%= f.password_field :password, required: true %>
            </div>
            <div class="col-md-4">
              <%= f.label :password_confirmation, class: "required" %>
              <%= f.password_field :password_confirmation, required: true %>
            </div>
          </div>
          <div class="pull-right">
            <%= f.submit nil, :class => "btn btn-primary" %>
          </div>
      <% end %>
    </div>
  </div>
</section>